### ISSUE TITLE
Move tests of assess_engagement from DAOlytics and add more tests

### ISSUE THREAD

**Issue by amindadgar** [TogetherCrew/core-analyzer-lib#5]
As part of the migration job, we need to move the tests written in DAOlytics repository related to `assess_engagement.py` to this repository and write more if needed.

```[tasklist]
### Tasks
- [x] Move related tests from DAOlytics
- [x] Add unit test for Activity enum class
- [x] Add unit test for networkx graph creation
- [x] Add unit test for `assess_active.py`
- [x] Add unit test for `assess_vital.py`
- [x] Add unit test for `assess_connected.py`
- [x] Add unit test for `assess_consistent.py`
- [x] Add unit test for `assess_dropped.py`
- [x] Add unit test for `assess_lurker.py`
- [x] Add unit test for `assess_overlap.py`
- [x] Add unit test for paused category of `assess_remainder.py`
- [x] Add unit test for `assess_still_active.py`
- [x] Add unit test for `check_past.py`
- [x] Add unit test for `check_prev_period.py`
- [x] Add unit test for `unpaused` category of `assess_remainder.py`
- [x] Add unit test for `returned` category of `assess_remainder.py`
- [x] Add unit test for `all_disengaged_in_past` category of `assess_remainder.py`
- [x] Add unit test for `all_new_disengaged` category of `assess_remainder.py`
- [x] Add unit test for `all_disengaged` category of `assess_remainder.py`
```
